### ISSUE TITLE
Errors in template variable queries are not shown in the dashboard

### ISSUE THREAD

**Issue by ryantxu** [grafana/timestream-datasource#101]
When defining a template variable query with timestream, if an error exists nothing is shown in the dashboard and may behave inconsistently over time.

This may be general grafana issues, or template variable queries need to re-throw any exceptions.

**Comment by sunker** [comment]
Do you know what kind of error in the template variable query? Also, do you know in what way it may behave inconsistently over time? 

This is what I've tested: 
1. Create a template variable query, name, that returns a 400 error.   
2. Use that in a raw sql query, e.g `select * from $__database.$__table where measure_name = '$name' limit 100`

In this case when the template variable query doesn't return any results, `measure_name = '$name'` will be interpolated to `measure_name = ''` which is valid query. I'm not sure what the expected behavior would be here? From what I understand, the panel editor knows in which query rows the template variables are being used. Shouldn't it then stop queries that use broken template variables from being executed? 

Non related to this problem, but shouldn't template variable query values be interpolated with wrapping singlequotes? If not, template variable queries won't be possible to use in string comparisons (at least not without regex magic). 
Eg `... where region in ($regions)`

**Comment by sudiptodas** [comment]
There are multiple issues happening here.

1. If there is an error with a template variable (either 4xx or 5xx), the user of the dashboard doesn't see any notification and the template variable is empty. This is very confusing for the users. If a panel query encounters an errors it is shown clearly with an error message. We need to make it clear to the user that loading the template variable itself encountered the error, and what the error was, so they can appropriately reload the variable.
2. How is a template variable which was not populated used in a query, which in turn results in the next wave of errors.

If we address 1 properly, maybe 2 will be handled with it, as the users will know that the template variable encountered an issue and hence probably dependent panels will fail/not have correct results.
